name: GitHub Actions After Push Into Develop Branch
on:
  push:
    branches:
      - develop
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install node
        uses: actions/setup-node@v4
        with:
           node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run:  npx playwright install --with-deps

      - name: Run tests 
        run: npx playwright test. Run npx playwright test
